---
# handlers file for ansible-squid
- name: restart squid3
  service: name=squid3 state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: restart haproxy
  service: name=haproxy state=restarted
